query GetLists($boardId: ID!) {
    getLists(boardId: $boardId) {
        id
        order
        name
        color
        board
        items {
            id
            order
            title
            complete
            dueDate
            body
            list
            subtasks {
                id
                order
                value
                checked
            }
            labels {
                id
                name
                color
            }
        }
    }
}
